In [3]:
import numpy as np

a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
s = a.sum(axis=1).reshape(-1, 1)
s

array([[ 6],
       [15],
       [24]])

In [10]:
np.tile(s, (1,a.shape[1]))

array([[ 6,  6,  6],
       [15, 15, 15],
       [24, 24, 24]])

In [6]:
a.shape

(3, 3)

In [7]:
np.exp(a).shape

(3, 3)

In [8]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
out = a.sum(axis=1, keepdims=True)
out

array([[ 6],
       [15],
       [24]])

In [33]:
np.repeat(out, a.shape[1], axis=1)


AxisError: axis 1 is out of bounds for array of dimension 1

In [36]:
np.tile(out, (1, a.shape[1]))

array([[ 6,  6,  6],
       [15, 15, 15],
       [24, 24, 24]])

In [25]:
b = np.sum(a, axis=1).reshape(-1, 1)

array([[ 6],
       [15],
       [24]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])