In [ ]:
import numpy as np

a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
s = a.sum(axis=1).reshape(-1, 1)
s

array([[ 6],
       [15],
       [24]])

In [10]:
np.tile(s, (1,a.shape[1]))

array([[ 6,  6,  6],
       [15, 15, 15],
       [24, 24, 24]])