In [1]:
import numpy as np

a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
s = a.sum(axis=1).reshape(-1, 1)
s

array([[ 6],
       [15],
       [24]])

In [10]:
np.tile(s, (1,a.shape[1]))

array([[ 6,  6,  6],
       [15, 15, 15],
       [24, 24, 24]])

In [6]:
a.shape

(3, 3)

In [7]:
np.exp(a).shape

(3, 3)

In [35]:
out = a.sum(axis=1, keepdims=True)
out

array([[ 6],
       [15],
       [24]])

In [36]:
np.tile(out, (1, a.shape[1]))

array([[ 6,  6,  6],
       [15, 15, 15],
       [24, 24, 24]])

In [25]:
b = np.sum(a, axis=1).reshape(-1, 1)

array([[ 6],
       [15],
       [24]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a = np.random.randn(4, 3, 2, 1)
b = np.random.randn(5, 3, 2, 1)

b.shape

(5, 3, 2, 1)

In [6]:
b.shape

(5, 3, 2, 1)

In [12]:
b = b[:, :, 1, 0]
b.shape

(5, 3)

In [24]:
a = np.random.randn(1, 3, 6, 7, 8)
a.shape

(1, 3, 6, 7, 8)

In [15]:
b * a

ValueError: operands could not be broadcast together with shapes (5,3) (1,3,6,7,8) 

In [17]:
(b[:, :, np.newaxis, np.newaxis, np.newaxis] * a).shape

(5, 3, 6, 7, 8)

In [21]:
a = a[:, :, 1, 0, 0, np.newaxis,np.newaxis ,np.newaxis]

a.shape

(1, 3, 1, 1, 1)

In [22]:
a

array([[[[[-1.23616169]]],


        [[[-1.24843556]]],


        [[[ 0.2835265 ]]]]])

In [25]:
a.shape

(1, 3, 6, 7, 8)